### ISSUE TITLE
Some suggestions regarding the repo and the Heat Failure Death post

### ISSUE THREAD

**Issue by hongtaoh** [Yumian-Cui/yumian-cui.github.io#2]
- Why not just have two branches, namely, `master` and `gh-pages` and make `master` the default one. Right now, the `main` is the default but it's empty. New comers to this repo will think this is an empty one. 

- In terms of [Heart Failure Death](https://yumian-cui.github.io/data_challenge_2020/):
   1. The report (https://yumian-cui.github.io/pdf/Data_Challenge_Report.pdf) seems to be empty. 
   2. Why not make each page in the [presentation](https://yumian-cui.github.io/pdf/Presentation.pdf) an image and put these images in [the post](https://yumian-cui.github.io/data_challenge_2020/). This way, a visitor can get the most of the information by a simple glance.

**Comment by Yumian-Cui** [comment]
Thanks for your suggestions, Hongtao! Now the main branch has been deleted and the default is set to master. I've updated the pdf and embedded google slides into my post.
